world_origin:

  units: "LATLON" # {"UTM, "LATLON"}

  origin_x: 49.28754
  origin_y: 14.12814

safety_area:

  enabled: false

  horizontal:

    # the frame of reference in which the points are expressed
    frame_name: "latlon_origin"

    # polygon
    #
    # x, y [m] for any frame_name except latlon_origin
    # x = latitude, y = longitude [deg]  for frame_name=="latlon_origin"
    points: []

  vertical:

    # the frame of reference in which the max&min z is expressed
    frame_name: "world_origin"

    max_z: 30.0
    min_z: 1.0
